apiVersion: apps/v1
kind: Deployment
metadata:
  name: kimager
  namespace: {{ .Release.Namespace }}
  labels:
    app: kimager
spec:
  replicas: {{ default 1 .Values.replicaCount }}
  selector:
    matchLabels:
      app: kimager
  template:
    metadata:
        labels:
          app: kimager
    spec:
      serviceAccountName: kimager
      containers:
        - name: kimager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ default "Always" .Values.image.pullPolicy }}
          {{- if .Values.logLevel }}
          env:
            - name: RUST_LOG
              value: {{ .Values.logLevel }}
          {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
