apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "{{ .Values.name }}-clusterrole"
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: "{{ .Values.name }}-clusterrolebinding"
subjects:
- kind: ServiceAccount
  name: "{{ .Values.name }}-serviceaccount"
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: "{{ .Values.name }}-clusterrole"
  apiGroup: rbac.authorization.k8s.io
